// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution(arg1) {
  return window['go']['main']['App']['CancelExecution'](arg1);
}

export function CleanupLogs(arg1) {
  return window['go']['main']['App']['CleanupLogs'](arg1);
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function CreateChatSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChatSession'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteAnalysisRecord(arg1) {
  return window['go']['main']['App']['DeleteAnalysisRecord'](arg1);
}

export function DeleteChatSession(arg1) {
  return window['go']['main']['App']['DeleteChatSession'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteHistoricalLogs() {
  return window['go']['main']['App']['DeleteHistoricalLogs']();
}

export function ExecuteWorkflow(arg1, arg2) {
  return window['go']['main']['App']['ExecuteWorkflow'](arg1, arg2);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function GetAnalysisHistory(arg1) {
  return window['go']['main']['App']['GetAnalysisHistory'](arg1);
}

export function GetAnalysisResult(arg1) {
  return window['go']['main']['App']['GetAnalysisResult'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetChatSession(arg1) {
  return window['go']['main']['App']['GetChatSession'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocumentContent(arg1) {
  return window['go']['main']['App']['GetDocumentContent'](arg1);
}

export function GetDocuments(arg1) {
  return window['go']['main']['App']['GetDocuments'](arg1);
}

export function GetLogDirectory() {
  return window['go']['main']['App']['GetLogDirectory']();
}

export function GetModels(arg1) {
  return window['go']['main']['App']['GetModels'](arg1);
}

export function GetModelsWithConfig(arg1) {
  return window['go']['main']['App']['GetModelsWithConfig'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorkflowDefinition(arg1) {
  return window['go']['main']['App']['GetWorkflowDefinition'](arg1);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ImportDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportDocument'](arg1, arg2, arg3);
}

export function ListChatSessions() {
  return window['go']['main']['App']['ListChatSessions']();
}

export function NewWorkflowDefinition() {
  return window['go']['main']['App']['NewWorkflowDefinition']();
}

export function QuickChat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['QuickChat'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameChatSession(arg1, arg2) {
  return window['go']['main']['App']['RenameChatSession'](arg1, arg2);
}

export function SaveWorkflowDefinition(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkflowDefinition'](arg1, arg2);
}

export function SelectDocuments() {
  return window['go']['main']['App']['SelectDocuments']();
}

export function SendChatMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SendDocumentChatMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendDocumentChatMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopChatGeneration(arg1) {
  return window['go']['main']['App']['StopChatGeneration'](arg1);
}

export function TestModelConnection(arg1, arg2) {
  return window['go']['main']['App']['TestModelConnection'](arg1, arg2);
}

export function TestModelConnectionWithConfig(arg1, arg2) {
  return window['go']['main']['App']['TestModelConnectionWithConfig'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateDocumentMeta(arg1, arg2) {
  return window['go']['main']['App']['UpdateDocumentMeta'](arg1, arg2);
}
