// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {storage} from '../models';
import {workflow} from '../models';
import {config} from '../models';
import {document} from '../models';

export function CancelExecution(arg1:string):Promise<void>;

export function CleanupLogs(arg1:number):Promise<number>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CreateChatSession(arg1:string,arg2:string,arg3:string):Promise<ai.ChatSession>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<storage.Workspace>;

export function DeleteAnalysisRecord(arg1:string):Promise<void>;

export function DeleteChatSession(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeleteHistoricalLogs():Promise<number>;

export function ExecuteWorkflow(arg1:string,arg2:Record<string, any>):Promise<string>;

export function ExportLogs():Promise<string>;

export function ExportReport(arg1:string,arg2:string):Promise<string>;

export function GetAnalysisHistory(arg1:string):Promise<Array<workflow.ExecutionRecord>>;

export function GetAnalysisResult(arg1:string):Promise<workflow.ExecutionResult>;

export function GetChatHistory(arg1:string):Promise<Array<ai.Message>>;

export function GetChatSession(arg1:string):Promise<ai.ChatSession>;

export function GetConfig():Promise<config.Config>;

export function GetDocument(arg1:string):Promise<document.Document>;

export function GetDocumentContent(arg1:string):Promise<string>;

export function GetDocuments(arg1:string):Promise<Array<document.Document>>;

export function GetLogDirectory():Promise<string>;

export function GetModels(arg1:string):Promise<Array<ai.ModelInfo>>;

export function GetModelsWithConfig(arg1:config.ProviderConfig):Promise<Array<ai.ModelInfo>>;

export function GetProviders():Promise<Array<ai.ProviderInfo>>;

export function GetVersion():Promise<string>;

export function GetWorkflowDefinition(arg1:string):Promise<workflow.WorkflowEditorData>;

export function GetWorkflows():Promise<Array<workflow.WorkflowInfo>>;

export function GetWorkspaces():Promise<Array<storage.Workspace>>;

export function ImportDocument(arg1:string,arg2:string,arg3:Array<string>):Promise<document.Document>;

export function ListChatSessions():Promise<Array<ai.ChatSession>>;

export function NewWorkflowDefinition():Promise<workflow.WorkflowEditorData>;

export function QuickChat(arg1:string,arg2:string,arg3:Array<ai.Message>,arg4:number,arg5:number):Promise<ai.ChatResponse>;

export function RenameChatSession(arg1:string,arg2:string):Promise<ai.ChatSession>;

export function SaveWorkflowDefinition(arg1:string,arg2:string):Promise<workflow.WorkflowEditorData>;

export function SelectDocuments():Promise<Array<string>>;

export function SendChatMessage(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<ai.ChatResponse>;

export function SendDocumentChatMessage(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number,arg6:boolean):Promise<ai.ChatResponse>;

export function StopChatGeneration(arg1:string):Promise<void>;

export function TestModelConnection(arg1:string,arg2:string):Promise<ai.ConnectionTestResult>;

export function TestModelConnectionWithConfig(arg1:config.ProviderConfig,arg2:string):Promise<ai.ConnectionTestResult>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function UpdateDocumentMeta(arg1:string,arg2:Record<string, any>):Promise<void>;
